title = "陈三"
lang = "zh"
description = "记录人、事与代码"
author = "陈三"
url = "https://blog.zfanw.com"
toc = true
theme = "@okmarvin/january"
themeColor = "#ffd54f"
github = "chenxsan"
# google_analytics = "UA-19839258-14"
paginate = 10
favicon = "/static/img/favicon.ico"
logo = "/static/img/logo.svg"
source = "https://github.com/chenxsan/blog.zfanw.com/blob/master/"


[[menu]]
text = "Home"
permalink = "/"

[[menu]]
text = "看书"
permalink = "/read/"

[[menu]]
text = "About"
permalink = "/about/"